version: '3.8'
services:
  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5434:5432"
    volumes:
      - "./database/postgres-data:/var/lib/postgresql/data:rw"
    restart: unless-stopped


